branches:
  except:
    - /^issue\d+/
    - /^gh\d+/
language: perl
matrix:
   fast_finish: true
   allow_failures:
     - perl: 5.28
       env: COVERAGE=1
     - perl: "blead"
env:
  global:
    - PERL_USE_UNSAFE_INC=0
    - AUTHOR_TESTING=1
    - AUTOMATED_TESTING=1
    - RELEASE_TESTING=1
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
script:
  - perl Makefile.PL && make test
before_install:
  - rm -f dist.ini # force to use Makefile.PL for faster smoke time
  - eval $(curl https://travis-perl.github.io/init) --auto
