#!/usr/local/bin/perl
package FastGlob;

require 5.005;

# ABSTRACT: A faster glob() implementation

BEGIN {
    # VERSION: generated by DZP::OurPkgVersion
}

=head1 SYNOPSIS

        use FastGlob qw(glob);
        my @list = &glob('*.c');

=head1 DESCRIPTION

This module implements globbing in perl, rather than forking a csh.
This is faster than the built-in glob() call, and more robust (on
many platforms, csh chokes on C<echo *> if too many files are in the
directory.)

There are several module-local variables that control platform-specific
behavior. On Windows (C<$^O eq 'MSWin32'>), these are automatically set
to appropriate values. On other platforms, UNIX defaults are used.
You can override them after loading the module if needed.

        # UNIX defaults (auto-detected):
        $FastGlob::dirsep = '/';        # directory path separator
        $FastGlob::rootpat = '\A\Z';    # root directory prefix pattern
        $FastGlob::curdir = '.';        # name of current directory in dir
        $FastGlob::parentdir = '..';    # name of parent directory in dir
        $FastGlob::hidedotfiles = 1;    # hide filenames starting with .

        # Windows defaults (auto-detected on MSWin32):
        $FastGlob::dirsep = '\\';       # directory path separator
        $FastGlob::rootpat = '[A-Z]:';  # <Drive letter><colon> pattern
        $FastGlob::curdir = '.';        # name of current directory in dir
        $FastGlob::parentdir = '..';    # name of parent directory in dir
        $FastGlob::hidedotfiles = 0;    # hide filenames starting with .

For classic MacOS you would set:

        $FastGlob::dirsep = ':';        # directory path separator
        $FastGlob::rootpat = '\A\Z';    # root directory prefix pattern
        $FastGlob::curdir = '.';        # name of current directory in dir
        $FastGlob::parentdir = '..';    # name of parent directory in dir
        $FastGlob::hidedotfiles = 0;    # hide filenames starting with .

Tilde expansion (C<~> and C<~user>) uses C<getpwuid>/C<getpwnam> on UNIX.
On Windows, C<~> falls back to C<$HOME> or C<$USERPROFILE>.

=head1 INSTALLATION

Copy this module to the Perl 5 Library directory.

=cut

use Exporter ();

@ISA = qw(Exporter);
@EXPORT = qw(&glob);
@EXPORT_OK = qw(dirsep rootpat curdir parentdir hidedotfiles);

use 5.004;
use strict;                # be good
use Carp qw(carp);

# platform specifics — auto-detect Windows defaults

our $dirsep       = ( $^O eq 'MSWin32' ) ? '\\' : '/';
our $rootpat      = ( $^O eq 'MSWin32' ) ? '[A-Z]:' : '\A\Z';
our $curdir       = '.';
our $parentdir    = '..';
our $hidedotfiles = ( $^O eq 'MSWin32' ) ? 0 : 1;
our $verbose      = 0;

#
# recursively wildcard expand a list of strings
#

sub glob {

    my @res; 
    my $part;
    my $found1;
    my $out;
    my $bracepat = qr(\{([^\{\}]*)\});

    # deal with {xxx,yyy,zzz} 
    @res = ();
    $found1 = 1;
    while ($found1) {
    $found1 = 0;
    for (@_) {
        if ( m{$bracepat} ) {
        foreach $part (split(',',$1)) {
            $out = $_;
            $out =~ s/$bracepat/$part/;
            push(@res, $out);
        }
        $found1 = 1;
        } else {
        push(@res, $_);
        }
    }
    @_ = @res;
        @res = ();
    }


    for (@_) {
    # check for and do  tilde expansion
    if ( /^\~([^\Q${dirsep}\E]*)/ ) {
        my $usr = $1;
        my $usrdir;
        if ( $usr eq "" ) {
            # ~ alone: try getpwuid, fall back to $HOME / $USERPROFILE
            $usrdir = eval { (getpwuid($<))[7] };
            if ( !defined $usrdir ) {
                $usrdir = defined $ENV{HOME} ? $ENV{HOME} : $ENV{USERPROFILE};
            }
        } else {
            # ~user: try getpwnam (not available on Windows)
            $usrdir = eval { (getpwnam($usr))[7] };
        }
        if ( defined $usrdir && $usrdir ne "" ) {
                s/^\~\Q$usr\E/$usrdir/;
        push(@res, $_);
        }
    } else {
        push(@res, $_);
        }
    }
    @_ = @res;
    @res = ();

    for (@_) {
    # if there's no wildcards, just return it
        unless (/(?<!\\)[*?\[\]{}]/) {
        push (@res, $_);
        next;
        }

    # Make the glob into a regexp
    # escape + , and | 
    s/([+.|])/\\$1/go;

    # handle * and ?
    s/(?<!\\)(\*)/.*/go;
    s/(?<!\\)(\?)/./go;

    # deal with dot files
    if ( $hidedotfiles ) {
        s/(\A|\Q$dirsep\E)\.\*/$1(?:[^.].*)?/g;
        s/(\A|\Q$dirsep\E)\./$1\[\^.\]/g;
        s/(\A|\Q$dirsep\E)\[\^([^].]*)\]/$1\[\^\\.$2\]/g;
    }

    # debugging
    print "regexp is $_\n" if ($verbose);

    # now split it into directory components
    my @comps = split(/\Q$dirsep\E/);

    if ( $comps[0] =~ /($rootpat)/ ) {
        shift(@comps);
        push(@res, &recurseglob( "$1$dirsep", "$1$dirsep" , @comps ));
    }
    else {
        push(@res, &recurseglob( $curdir, '' , @comps ));
    }
    }
    return sort(@res);
}

sub recurseglob {
    my($dir, $dirname, @comps) = @_;
    my(@res) = ();
    my($re, $anymatches, @names);


    if ( @comps == 0 ) {
        # bottom of recursion, just return the path 
        chop($dirname);  # always has gratiutous trailing slash
        @res = ($dirname);
    } elsif ($comps[0] eq '') {
        shift(@comps);
    unshift(@res, &recurseglob( "$dir$dirsep", 
                    "$dirname$dirsep",
                    @comps ));
    } else {
        $re = '\A' . shift(@comps) . '\Z';

        # slurp in the directory
        if (!opendir(HANDLE, $dir)) {
            carp "FastGlob: opendir '$dir' failed: $!" if $verbose;
            return @res;
        }
        @names = readdir(HANDLE);
        closedir(HANDLE);

        # look for matches, and if you find one, glob the rest of the
        # components. We eval the loop so the regexp gets compiled in,
        # making searches on large directories faster.
        $anymatches = 0;
        print "component re is qr($re)\n" if ($verbose);
        my $regex = qr($re);
    foreach (@names) {
        print "considering |$_|\n" if ($verbose);
        if ( m{$regex} ) {
        if ( $#comps > -1 ) {
            unshift(@res, &recurseglob( "$dir$dirsep$_", 
                        "$dirname$_$dirsep",
                        @comps ));
        } else {
            unshift(@res, "$dirname$_" );
        }
        $anymatches = 1;
        }
    }
    }
    return @res;
}

1;
__END__
